function: connectors.{{cookiecutter.connector_name}}.src.validation.validate_{{cookiecutter.pipeline_stage_abbr}}{{cookiecutter.node_name}}.validate_{{cookiecutter.pipeline_stage_abbr}}{{cookiecutter.node_name}}
inputs:
  - {{cookiecutter.pipeline_stage_abbr}}{{cookiecutter.node_name}}
  - {{cookiecutter.ref_data_abbr}}{{cookiecutter.pipeline_stage_abbr}}{{cookiecutter.node_name}}
name: validate_{{cookiecutter.pipeline_stage_abbr}}{{cookiecutter.node_name}}
